comments :
  provider : disqus
  disqus :
    short_name : supercafe

markdown: kramdown
highlighter: pygments
permalink: date

url:
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed