markdown: kramdown
highlighter: pygments
permalink: date

title : Erica's Blog-生活、学习、思考

categories_path : /categories.html
tags_path : /tags.html

url:
baseurl:

BASE_PATH : false

ASSET_PATH : false

JB :
  version : 0.3.0


sass:
  sass_dir: public/css
  style: :compressed

     
comments :
  provider : disqus
  disqus :
    short_name : jekyllbootstrap
  livefyre :
    site_id : 123
  intensedebate :
    account : 123abc
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light
    
analytics :
    provider : google 
    google : 
        tracking_id : 'UA-123-12'
    getclicky :
      site_id : 
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'                   # the id of the site on Piwik