markdown: kramdown
highlighter: pygments
permalink: date

title : Erica's Blog-Life&Technology

categories_path : /categories.html
tags_path : /tags.html

url:
baseurl:

JB :
  version : 0.3.0


sass:
  sass_dir: public/css
  style: :compressed

comments :
    provider : duoshuo
    duoshuo :
      short_name : simpleyyt
    disqus :
      short_name : simpleyyt
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light
    